interknot_level = 60
control_avatar_id = 2011
control_guise_avatar_id = 1371
day_of_week = 5
start_main_quest = false
default_section_id = 1

[avatar]
unlock_all = true
unlock_id_list = [ 1011, 1081 ]
level = 60
rank = 6
unlocked_talent_num = 0
talent_switch = [ false, false, false, false, false, false ]
passive_skill_level = 7
skill_level_map = [ 12, 12, 12, 12, 7, 7, 12 ]

[weapon]
unlock_all = true
unlock_id_list = [ 13101 ]
level = 60
star = 5
refine_level = 1