["CNBetaWin2.0.4"]
design_data_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8386195_5dcc5dfa8e/client/"
design_data_revision = "8367035"
design_data_files = '[{"fileName": "data_version", "fileSize": 4488, "fileMD5": "2515569682238179856"}]'
game_res_url = "https://autopatchcn.juequling.com/game_res/beta_live/output_8386195_5dcc5dfa8e/client/"
game_res_branch = "beta_live"
game_audio_revision = "8338689"
game_res_revision = "8367035"
game_res_files = '[{"fileName": "res_version", "fileSize": 2139828, "fileMD5": "17743167981324637205"}, {"fileName": "audio_version", "fileSize": 30438, "fileMD5": "13945243646153886326"}, {"fileName": "base_revision", "fileSize": 18, "fileMD5": "16250874106773742342"}]'
silence_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8386195_5dcc5dfa8e/client_silence/"
silence_revision = "8386195"
silence_files = '[{"fileName": "silence_version", "fileSize": 645, "fileMD5": "6099549881367569487"}]'
