["CNBetaWin2.0.5"]
design_data_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8467486_0b761ffd42/client/"
design_data_revision = "8463451"
design_data_files = '[{"fileName": "data_version", "fileSize": 4499, "fileMD5": "6305425049584504292"}]'
game_res_url = "https://autopatchcn.juequling.com/game_res/beta_live/output_8467486_0b761ffd42/client/"
game_res_branch = "beta_live"
game_audio_revision = "8463040"
game_res_revision = "8467486"
game_res_files = '[{"fileName": "res_version", "fileSize": 2151564, "fileMD5": "2646718624318704971"}, {"fileName": "audio_version", "fileSize": 30443, "fileMD5": "18070033365372759751"}, {"fileName": "base_revision", "fileSize": 18, "fileMD5": "4402295285168915342"}]'
silence_url = "https://autopatchcn.juequling.com/design_data/beta_live/output_8467486_0b761ffd42/client_silence/"
silence_revision = "8463040"
silence_files = '[{"fileName": "silence_version", "fileSize": 410, "fileMD5": "17228964297244659932"}]'
