bound_sid = 1

[[servers]]
sid = 1
bind_version = "CNBetaWin2.0.5"
name = "vivian_rs"
title = "Vivian-RS"
dispatch_url = "http://127.0.0.1:10100/query_gateway"
dispatch_seed = "391fcd4268c6cbf8"
gateway_ip = "127.0.0.1"
gateway_port = 20501
